### ISSUE TITLE
Decoded tags containing parenthesis in their name get parsed incorrectly

### ISSUE THREAD

**Issue by flvinny** [AbdyyEee/PylibMS#3]
https://github.com/AbdyyEee/PylibMS/blob/f993dee2f077f4ae7098ece10689fb82f240f836/LMS/Message/Tags.py#L31-L37
```py
>>> import LMS.Message.Tags
>>> LMS.Message.Tags.Tag_Utility.get_group_and_tag_names('<Reference::Counter(JP) buffer="14" type="Voice" counter="None">')
['Reference', 'Counter']
```

**Comment by AbdyyEee** [comment]
I'm currently in the process of refactoring a lot of the library, I think I know how I could fix this pretty easily.

**Comment by AbdyyEee** [comment]
Recent refactors fixed this.
